Repository union-group/fadeapp, pull requests merged in 2022-11, with the labels that each got.

#115 docs: update readme info
  README.md
Labels: documentation

#87 feat: add FormModal on Hero
  src/components/Form/FormModal/__snapshots__/test.tsx.snap
  src/components/Form/FormModal/index.tsx
  src/components/Form/FormModal/stories.tsx
  src/components/Form/FormModal/styles.ts
  src/components/Form/FormModal/test.tsx
  src/components/Hero/__snapshots__/test.tsx.snap
  src/components/Hero/index.tsx
  src/components/Hero/test.tsx
  tailwind.config.js
Labels: feat

#86 fix: adjust hover plan card
  src/components/Cards/PlanCard/__snapshots__/test.tsx.snap
  src/components/Cards/PlanCard/styles.ts
Labels: bug

#118 feat: create query for get main page data
  src/graphql/queries/index.ts
Labels: feat

#125 fix: adjust Chatboot layout on mobile
  src/components/Chatboot/ChatbootButton/__snapshots__/test.tsx.snap
  src/components/Chatboot/ChatbootButton/styles.ts
  src/components/Chatboot/ChatbootModal/__snapshots__/test.tsx.snap
  src/components/Chatboot/ChatbootModal/styles.ts
  tailwind.config.js
Labels: fix

#126 feat: add dynamic data on Main page
  next.config.js
  src/graphql/generated/graphql.ts
  src/graphql/queries/index.ts
  src/pages/index.tsx
Labels: feat

#130 fix: mapper-generator-template
  plop/templates/mapper/test.ts.hbs
Labels: fix

#119 feat: create mapper for menu
  src/mappers/menu/index.ts
  src/mappers/menu/test.ts
  src/pages/index.tsx
Labels: feat

#133 fix: change menu type of menu mapper
  src/mappers/menu/index.ts
  src/mappers/menu/test.ts
Labels: fix

#131 feat: create mapper for hero
  src/mappers/hero/index.ts
  src/mappers/hero/test.ts
  src/pages/index.tsx
  src/types/graphql.ts
Labels: feat

#129 fix: remove after line of last testimonial
  src/components/Cards/TestimonialCard/__snapshots__/test.tsx.snap
  src/components/Cards/TestimonialCard/styles.ts
  src/components/Slider/styles.ts
  src/components/Slider/templates/SliderItemTemplate.tsx
Labels: fix

#132 feat: create mapper for testimonials
  src/mappers/testimonials/index.ts
  src/mappers/testimonials/test.ts
  src/pages/index.tsx
  src/types/graphql.ts
Labels: feat, high

#136 feat: create mapper for footerSection
  src/mappers/footer/index.ts
  src/mappers/footer/test.ts
  src/pages/index.tsx
  src/types/graphql.ts
Labels: feat, high

#137 feat: create mapper for planSection
  src/mappers/planSection/index.ts
  src/mappers/planSection/test.ts
  src/pages/index.tsx
  src/types/graphql.ts
Labels: feat, high
