Repository union-group/fadeapp, pull requests merged in 2022-10, with the labels that each got.

#67 fix: add z-index to Header
  src/components/Header/__snapshots__/test.tsx.snap
  src/components/Header/styles.ts
Labels: fix

#66 fix: add z-index to chatboot
  src/components/ChatbootButton/__snapshots__/test.tsx.snap
  src/components/ChatbootButton/styles.ts
  src/components/ChatbootModal/__snapshots__/test.tsx.snap
  src/components/ChatbootModal/styles.ts
Labels: fix

#65 fix: removing scale animation
  src/components/PlanCard/__snapshots__/test.tsx.snap
  src/components/PlanCard/styles.ts
Labels: fix

#72 fix: fixed the problem in the background image
  src/components/PlanCard/__snapshots__/test.tsx.snap
  src/components/PlanCard/styles.ts
Labels: fix

#74 fix: fixing slider styles
  src/components/Slider/__snapshots__/test.tsx.snap
  src/components/Slider/index.tsx
  src/components/Slider/styles.ts
Labels: fix

#73 fix: add arrow slider spacing
  src/components/Slider/__snapshots__/test.tsx.snap
  src/components/Slider/styles.ts
Labels: fix

#75 fix: fixing testimonials styles and add placeholder to next image com…
  src/components/TestimonialCard/__snapshots__/test.tsx.snap
  src/components/TestimonialCard/index.tsx
  src/components/TestimonialCard/styles.ts
Labels: fix

#64 feat: create landing page
  next.config.js
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/mstile-150x150.png
  src/components/Hero/mock.ts
  src/components/Hero/stories.tsx
  src/components/PlanCard/mock.ts
  src/components/PlanCard/stories.tsx
  src/layout/Home/index.tsx
  src/layout/Main/index.tsx
  src/layout/Main/styles.ts
  src/layout/Main/templates/PlanCardTemplate.tsx
  src/layout/Main/test.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  tailwind.config.js
Labels: feat

#88 fix: Adjust mobile layout
  src/components/Cards/PlanCard/__snapshots__/test.tsx.snap
  src/components/Cards/PlanCard/styles.ts
  src/components/Cards/TestimonialCard/__snapshots__/test.tsx.snap
  src/components/Cards/TestimonialCard/styles.ts
  src/components/Headline/__snapshots__/test.tsx.snap
  src/components/Headline/styles.ts
  src/components/Headline/test.tsx
  src/components/Hero/__snapshots__/test.tsx.snap
  src/components/Hero/styles.ts
  src/layout/Main/styles.ts
Labels: fix

#90 docs: updating readme
  README.md
Labels: documentation

#85 fix: change headline of hero
  src/components/Hero/__snapshots__/test.tsx.snap
  src/components/Hero/index.tsx
Labels: bug

#92 chore: add webpack dependencies
  package.json
  yarn.lock
Labels: dependencies, Chore

#109 fix: add missing id prop on TestimonialCard
  src/components/Cards/TestimonialCard/index.tsx
  src/components/Cards/TestimonialCard/mock.ts
Labels: fix

#95 fix: adjust Slider
  package.json
  src/components/Slider/__snapshots__/test.tsx.snap
  src/components/Slider/config.ts
  src/components/Slider/index.tsx
  src/components/Slider/styles.ts
  src/components/Slider/templates/SliderItemTemplate.tsx
  src/components/Slider/test.tsx
  src/hooks/useMediaQuery.ts
  yarn.lock
Labels: fix
